version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.4
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-scripts:/etc/localstack/init/ready.d"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: gallery
      POSTGRES_PASSWORD: gallerypass
      POSTGRES_DB: gallery
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  image-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-service
    depends_on:
      - postgres
      - localstack
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gallery
      SPRING_DATASOURCE_USERNAME: gallery
      SPRING_DATASOURCE_PASSWORD: gallerypass
      AWS_S3_ENDPOINT: http://localstack:4566
      AWS_S3_BUCKET: images
      AWS_REGION: us-east-1
    ports:
      - "8083:8083"

volumes:
  pg-data:
