server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: gallery
    password: gallerypass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: us-east-1
    s3:
      endpoint: http://localstack:4566
      bucket: images
    stack:
      auto: false
